<h2>Tipos de datos</h2>

<h3>Primitivos</h3>

In [4]:
from datetime import datetime

integer_type = 42
float_type = 3.14159
bool_type = False
hex_type = 0xff
oct_type = 0o23
today = datetime.now()
str_type = 'Martin'

<h3>Estructurados</h3>

In [3]:
from IPython.display import Image

<h3>Semi Estructurados</h3>

<h3>No Estructurados</h3>

Importthis

<h2> Solicitudes a la Web </h2>

In [19]:
import requests

response = requests.get('https://www.platzi.com')

<h3> Extraccion de informacion del HTML </h3>

In [1]:
import bs4

soup = bs4.BeautifulSoup(response.text, 'html.parser')
#print(soup.title.text)

#print(soup.select('meta[name=description]')[0]['content'])
courses_links = soup.select('.CarrersList')
courses = [course['href'] for course in courses_links]

for course in courses:
    print(course)

NameError: name 'response' is not defined

<h3>Series</h3>

In [5]:
import pandas as pd

series_test = pd.Series([100, 200, 300])

series_test

0    100
1    200
2    300
dtype: int64

In [8]:
series_test2 = pd.Series({1999: 48, 
                          2000: 65, 
                          2001: 89})

series_test2

1999    48
2000    65
2001    89
dtype: int64

<h3>DataFrames</h3>

In [9]:
frame_test = pd.DataFrame({1999: [74, 38, 39],
                          2000: [34, 32, 32],
                          2001: [23, 39, 23]})
frame_test

   1999  2000  2001
0    74    34    23
1    38    32    39
2    39    32    23

In [11]:
frame_test2 = pd.DataFrame([[74, 38, 39],
                          [34, 32, 32],
                          [23, 39, 23]], columns = [1999, 2000, 2001])
frame_test2

   1999  2000  2001
0    74    38    39
1    34    32    32
2    23    39    23

<h3>Read data</h3>

In [35]:
#el_universal = pd.read_csv()
financias = pd.read_csv('Financial.csv')

financias

,Segment,Country,Product,DiscountBand,UnitsSold,ManufacturingPrice,SalePrice,GrossSales,Discounts,Sales,COGS,Profit,Date,MonthNumber,MonthName,Year
0,Government,UnitedStatesofAmerica,Paseo,Low,3450.0,$10.00,$350.00,"$1,207,500.00","$48,300.00","$1,159,200.00","$897,000.00","$262,200.00",7/1/2014,7,July,2014
1,Government,France,Amarilla,None,2750.0,$260.00,$350.00,"$962,500.00",$0.00,"$962,500.00","$715,000.00","$247,500.00",2/1/2014,2,February,2014
2,Government,Germany,Velo,Low,2966.0,$120.00,$350.00,"$1,038,100.00","$20,762.00","$1,017,338.00","$771,160.00","$246,178.00",10/1/2013,10,October,2013
3,Government,Germany,Amarilla,Low,2966.0,$260.00,$350.00,"$1,038,100.00","$20,762.00","$1,017,338.00","$771,160.00","$246,178.00",10/1/2013,10,October,2013
4,Government,Germany,Velo,Low,2877.0,$120.00,$350.00,"$1,006,950.00","$20,139.00","$986,811.00","$748,020.00","$238,791.00",10/1/2014,10,October,2014
5,Government,Germany,VTT,Low,2877.0,$250.00,$350.00,"$1,006,950.00","$20,139.00","$986,811.00","$748,020.00","$238,791.00",10/1/2014,10,October,2014
6,Government,Canada,Carretera,Low,2852.0,$3.00,$350.00,"$998,200.00","$19,964.00","$978,236.00","$741,520.00","$236,716.00",12/1/2014,12,December,2014
7,Government,Canada,Paseo,Low,2852.0,$10.00,$350.00,"$998,200.00","$19,964.00","$978,236.00","$741,520.00","$236,716.00",12/1/2014,12,December,2014
8,Government,France,Amarilla,Medium,2876.0,$260.00,$350.00,"$1,006,600.00","$70,462.00","$936,138.00","$747,760.00","$188,378.00",9/1/2014,9,September,2014
9,Government,France,Carretera,Low,2155.0,$3.00,$350.00,"$754,250.00","$7,542.50","$746,707.50","$560,300.00","$186,407.50",12/1/2014,12,December,2014
10,Government,France,Paseo,Low,2155.0,$10.00,$350.00,"$754,250.00","$7,542.50","$746,707.50","$560,300.00","$186,407.50",12/1/2014,12,December,2014
11,Government,France,Velo,Low,2177.0,$120.00,$350.00,"$761,950.00","$30,478.00","$731,472.00","$566,020.00","$165,452.00",10/1/2014,10,October,2014
12,Government,France,VTT,Low,2177.0,$250.00,$350.00,"$761,950.00","$30,478.00","$731,472.00","$566,020.00","$165,452.00",10/1/2014,10,October,2014
13,Government,Mexico,VTT,Low,1940.0,$250.00,$350.00,"$679,000.00","$13,580.00","$665,420.00","$504,400.00","$161,020.00",12/1/2013,12,December,2013
14,Government,Canada,Paseo,None,1725.0,$10.00,$350.00,"$603,750.00",$0.00,"$603,750.00","$448,500.00","$155,250.00",11/1/2013,11,November,2013
15,Government,UnitedStatesofAmerica,VTT,High,2807.0,$250.00,$350.00,"$982,450.00","$98,245.00","$884,205.00","$729,820.00","$154,385.00",8/1/2014,8,August,2014
16,Government,Germany,Amarilla,Low,1907.0,$260.00,$350.00,"$667,450.00","$26,698.00","$640,752.00","$495,820.00","$144,932.00",9/1/2014,9,September,2014
17,Government,France,Velo,Medium,2076.0,$120.00,$350.00,"$726,600.00","$43,596.00","$683,004.00","$539,760.00","$143,244.00",10/1/2013,10,October,2013
18,Government,France,Amarilla,Medium,2076.0,$260.00,$350.00,"$726,600.00","$43,596.00","$683,004.00","$539,760.00","$143,244.00",10/1/2013,10,October,2013
19,Government,Germany,Montana,Low,1797.0,$5.00,$350.00,"$628,950.00","$18,868.50","$610,081.50","$467,220.00","$142,861.50",9/1/2013,9,September,2013
20,Government,Mexico,Amarilla,Low,1865.0,$260.00,$350.00,"$652,750.00","$26,110.00","$626,640.00","$484,900.00","$141,740.00",2/1/2014,2,February,2014
21,Government,Mexico,Paseo,Medium,2417.0,$10.00,$350.00,"$845,950.00","$76,135.50","$769,814.50","$628,420.00","$141,394.50",1/1/2014,1,January,2014
22,Government,France,VTT,None,1527.0,$250.00,$350.00,"$534,450.00",$0.00,"$534,450.00","$397,020.00","$137,430.00",9/1/2013,9,September,2013
23,SmallBusiness,UnitedStatesofAmerica,Paseo,Low,2905.0,$10.00,$300.00,"$871,500.00","$8,715.00","$862,785.00","$726,250.00","$136,535.00",11/1/2014,11,November,2014
24,Government,Germany,Carretera,None,1513.0,$3.00,$350.00,"$529,550.00",$0.00,"$529,550.00","$393,380.00","$136,170.00",12/1/2014,12,December,2014
25,Government,Germany,Paseo,None,1513.0,$10.00,$350.00,"$529,550.00",$0.00,"$529,550.00","$393,380.00","$136,170.00",12/1/2014,12,December,2014
26,Government,Canada,Amarilla,Low,1778.0,$260.00,$350.00,"$622,300.00","$24,892.00","$597,408.00","$462,280.00","$135,128.00",12/1/2013,12,December,2013
27,Government,Germany,Paseo,Medium,2146.0,$10.00,$350.00,"$751,100.00","$60,088.00","$691,012.00","$557,960.00","$133,052.00",11/1/2013,11,November,2013
28,Government,Mexico,VTT,Low,1642.0,$250.00,$350.00,"$574,700.00","$17,241.00","$557,459.00","$426,920.00","$130,539.00",8/1/2014,8,August,2014
29,Government,UnitedStatesofAmerica,Montana,High,2313.0,$5.00,$350.00,"$809,550.00","$80,955.00","$728,595.00","$601,380.00","$127,215.00",5/1/2014,5,May,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,Enterprise,UnitedStatesofAmerica,Velo,High,1596.0,$120.00,$125.00,"$199,500.00","$19,950.00","$179,550.00","$191,520.00","-$11,970.00",9/1/2014,9,September,2014
671,Enterprise,France,Amarilla,High,1433.0,$260.00,$125.00,"$179,125.00","$19,703.75","$159,421.25","$171,960.00","-$12,538.75",5/1/2014,5,May,2014
672,Enterprise,France,Carretera,High,1023.0,$3.00,$125.00,"$127,875.00","$17,902.50","$109,972.50","$122,760.00","-$12,787.50",9/1/2013,9,September,2013
673,Enterprise,Germany,Paseo,Medium,3513.0,$10.00,$125.00,"$439,125.00","$30,738.75","$408,386.25","$421,560.00","-$13,173.75",7/1/2014,7,July,2014
674,Enterprise,Mexico,Velo,Medium,2110.0,$120.00,$125.00,"$263,750.00","$23,737.50","$240,012.50","$253,200.00","-$13,187.50",9/1/2014,9,September,2014
675,Enterprise,UnitedStatesofAmerica,Montana,High,1804.0,$5.00,$125.00,"$225,500.00","$22,550.00","$202,950.00","$216,480.00","-$13,530.00",11/1/2013,11,November,2013
676,Enterprise,Canada,Velo,High,1916.0,$120.00,$125.00,"$239,500.00","$23,950.00","$215,550.00","$229,920.00","-$14,370.00",12/1/2013,12,December,2013
677,Enterprise,Germany,Carretera,High,1085.0,$3.00,$125.00,"$135,625.00","$20,343.75","$115,281.25","$130,200.00","-$14,918.75",10/1/2014,10,October,2014
678,Enterprise,Germany,Paseo,High,1085.0,$10.00,$125.00,"$135,625.00","$20,343.75","$115,281.25","$130,200.00","-$14,918.75",10/1/2014,10,October,2014
679,Enterprise,France,Carretera,High,1174.0,$3.00,$125.00,"$146,750.00","$22,012.50","$124,737.50","$140,880.00","-$16,142.50",8/1/2014,8,August,2014
680,Enterprise,UnitedStatesofAmerica,Montana,Medium,2797.0,$5.00,$125.00,"$349,625.00","$31,466.25","$318,158.75","$335,640.00","-$17,481.25",12/1/2014,12,December,2014
681,Enterprise,UnitedStatesofAmerica,Paseo,Medium,2797.0,$10.00,$125.00,"$349,625.00","$31,466.25","$318,158.75","$335,640.00","-$17,481.25",12/1/2014,12,December,2014
682,Enterprise,Canada,Paseo,High,1583.0,$10.00,$125.00,"$197,875.00","$25,723.75","$172,151.25","$189,960.00","-$17,808.75",6/1/2014,6,June,2014
683,Enterprise,Canada,VTT,High,1583.0,$250.00,$125.00,"$197,875.00","$25,723.75","$172,151.25","$189,960.00","-$17,808.75",6/1/2014,6,June,2014
684,Enterprise,Canada,Amarilla,High,1659.0,$260.00,$125.00,"$207,375.00","$26,958.75","$180,416.25","$199,080.00","-$18,663.75",1/1/2014,1,January,2014
685,Enterprise,Canada,VTT,High,2529.0,$250.00,$125.00,"$316,125.00","$31,612.50","$284,512.50","$303,480.00","-$18,967.50",11/1/2014,11,November,2014
686,Enterprise,Mexico,Velo,High,1575.0,$120.00,$125.00,"$196,875.00","$27,562.50","$169,312.50","$189,000.00","-$19,687.50",2/1/2014,2,February,2014
687,Enterprise,France,Carretera,High,2441.0,$3.00,$125.00,"$305,125.00","$33,563.75","$271,561.25","$292,920.00","-$21,358.75",10/1/2014,10,October,2014
688,Enterprise,France,Paseo,High,2441.0,$10.00,$125.00,"$305,125.00","$33,563.75","$271,561.25","$292,920.00","-$21,358.75",10/1/2014,10,October,2014
689,Enterprise,Mexico,Carretera,High,2156.0,$3.00,$125.00,"$269,500.00","$32,340.00","$237,160.00","$258,720.00","-$21,560.00",10/1/2014,10,October,2014
690,Enterprise,Mexico,Paseo,High,2156.0,$10.00,$125.00,"$269,500.00","$32,340.00","$237,160.00","$258,720.00","-$21,560.00",10/1/2014,10,October,2014
691,Enterprise,UnitedStatesofAmerica,VTT,High,2387.0,$250.00,$125.00,"$298,375.00","$35,805.00","$262,570.00","$286,440.00","-$23,870.00",11/1/2014,11,November,2014
692,Enterprise,Canada,Carretera,High,2416.0,$3.00,$125.00,"$302,000.00","$36,240.00","$265,760.00","$289,920.00","-$24,160.00",9/1/2013,9,September,2013
693,Enterprise,UnitedStatesofAmerica,Carretera,High,3445.5,$3.00,$125.00,"$430,687.50","$43,068.75","$387,618.75","$413,460.00","-$25,841.25",4/1/2014,4,April,2014
694,Enterprise,Germany,Amarilla,High,3165.0,$260.00,$125.00,"$395,625.00","$43,518.75","$352,106.25","$379,800.00","-$27,693.75",1/1/2014,1,January,2014
695,Enterprise,UnitedStatesofAmerica,Velo,High,2438.0,$120.00,$125.00,"$304,750.00","$45,712.50","$259,037.50","$292,560.00","-$33,522.50",12/1/2013,12,December,2013
696,Enterprise,Mexico,Carretera,High,2821.0,$3.00,$125.00,"$352,625.00","$49,367.50","$303,257.50","$338,520.00","-$35,262.50",12/1/2013,12,December,2013
697,Enterprise,UnitedStatesofAmerica,Amarilla,High,2844.0,$260.00,$125.00,"$355,500.00","$49,770.00","$305,730.00","$341,280.00","-$35,550.00",5/1/2014,5,May,2014
698,Enterprise,Germany,Carretera,High,2767.0,$3.00,$125.00,"$345,875.00","$51,881.25","$293,993.75","$332,040.00","-$38,046.25",8/1/2014,8,August,2014
699,Enterprise,Canada,VTT,High,2954.0,$250.00,$125.00,"$369,250.00","$55,387.50","$313,862.50","$354,480.00","-$40,617.50",11/1/2013,11,November,2013

<h3>Index and selection</h3>

In [49]:
# Para traer alguna columna de preferencia
#el_universal['title']
#financias['Country']


###Columnas que queremos
#el_universal['title','url']
financias['Country','Product']


###numpy like
###Rango de items
#el_universal.iloc[10:15]
#financias.iloc[10]['Country']

###Fila de items y alguna columna
#el_universal.iloc[66]['title']

KeyError: ('Country', 'Product')